### ISSUE TITLE
3rd party integration

### ISSUE THREAD

**Issue by pawelpabich** [RichiCoder1/Browser.xUnit#3]
This is more a question. Will this new approach work with VS and/or R# test runner?

**Comment by RichiCoder1** [comment]
I'd need to document it, but simply adding the `TestFramework` attribute pointing to this framework does work w/ Resharper and VS. Actually ran into an issue where I put my global state setup too high up the chain and it would setup IIS every time Resharper scanned my assembly for tests.

**Comment by pawelpabich** [comment]
Awesome.
